### ISSUE TITLE
启动脚本错误

### ISSUE THREAD

**Issue by flowerpig2012** [TeaWeb/cluster#1]
检查一下启动脚本，脚本部分错误。我修改了一下。

#! /bin/bash
#
# teaweb-cluster       TeaWeb cluster console
#
# chkconfig: 2345 40 90
# description: TeaWeb cluster console

# teaweb cluster install dir
INSTALL_DIR=/opt/teaweb-cluster

case "$1" in
start)
    ${INSTALL_DIR}/bin/teaweb-cluster start
    ;;
stop)
    ${INSTALL_DIR}/bin/teaweb-cluster stop
    ;;
restart)
    ${INSTALL_DIR}/bin/teaweb-cluster restart
    ;;
status)
    ${INSTALL_DIR}/bin/teaweb-cluster status
    ;;
*)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 2
esac

**Comment by iwind** [comment]
fixed
